mlp:
  activation: relu
  dropout: 0.2
  hidden_dims:
  - 32
  - 16
  input_dim: 518
  n_embed_dim: 7
  n_features_per_group:
  - 84
  - 84
  - 84
  - 140
  - 7
  - 7
  - 7
  - 49
  - 7
  - 42
  - 7
  n_groups: 11
  output_dim: 8
  use_patch_embedding: false
transformer:
  dim_feedforward: 128
  dropout: 0.5
  input_dim: 518
  n_embed_dim: 16
  n_features_per_group:
  - 84
  - 84
  - 84
  - 140
  - 7
  - 7
  - 7
  - 49
  - 7
  - 42
  - 7
  n_groups: 11
  n_heads: 2
  num_layers: 3
  output_dim: 8
  use_patch_embedding: true
